export const CONTRACT_OPTIONS = [
  { centro_custo: '1394', contrato: 'CAMARA MUNIC. ARARAS - CT 013-23 - LP E CONS' },
  { centro_custo: '1360', contrato: 'COORDENADORIA DE PARQUES E PARCERIAS' },
  { centro_custo: '999',  contrato: 'DEMAX SERVICOS E COMERCIO LTDA' },
  { centro_custo: '1331', contrato: 'PENHA - LOGRADOURO' },
  { centro_custo: '1361', contrato: 'PQ CHUCRE-SEC M. AMBIENTE - SP LP/AV' },
  { centro_custo: '1382', contrato: 'PREF DO MUNICIPIO DE FRANCO DA ROCHA' },
  { centro_custo: '1391', contrato: 'PREF GUARAREMA - AREAS VERDES - PE 14-23' },
  { centro_custo: '1383', contrato: 'PREF HORTOLANDIA - LIMPEZA PREDIAL PE 169/2022' },
  { centro_custo: '1326', contrato: 'PREF. DE HORTOLÂNDIA - MANEJO ARBÓREO - 1326' },
  { centro_custo: '706',  contrato: 'PREF. DE MOGI DAS CRUZES - LIMPEZA PREDIAL - 706' },
  { centro_custo: '968',  contrato: 'PREF. DE MOGI DAS CRUZES - MANUTENÇÃO DE ÁREAS VERDES' },
  { centro_custo: '1373', contrato: 'PREFEITURA DO MUNICIPIO DE SAO PAULO' },
  { centro_custo: '1379', contrato: 'PREFEITURA DO MUNICIPIO DE VALINHOS' },
  { centro_custo: '1390', contrato: 'PREFEITURA MUNICIPAL DE ARARAS - AV E VARRICAO' },
  { centro_custo: '1397', contrato: 'PREFEITURA MUNICIPAL DE BERTIOGA' },
  { centro_custo: '1362', contrato: 'PREFEITURA MUNICIPAL DE CAMPINAS' },
  { centro_custo: '1398', contrato: 'PREFEITURA MUNICIPAL DE PORTO FELIZ' },
  { centro_custo: '1392', contrato: 'PREFEITURA SAO VICENTE - MANUT PREDIAL' },
  { centro_custo: '1401', contrato: 'SUBPREF ITAIM AV E MANEJO ARBOREO' },
  { centro_custo: '1405', contrato: 'SUBPREF. PENHA PICHACAO - REC SUP PICHADAS' },
  { centro_custo: '1407', contrato: 'SUBPREFEITURA ERMELINO MATARAZZO GALERIA' },
  { centro_custo: '1363', contrato: 'SUBPREFEITURA GUAIANASES' },
  { centro_custo: '1406', contrato: 'SUBPREFEITURA ITAIM GALERIAS / CT 14/SUB-IT/2025' },
  { centro_custo: '1404', contrato: 'SUBPREFEITURA VILA MARIA / VILA GUILHERME LOGRADOURO' },
  { centro_custo: '1408', contrato: 'UNIVERSIDADE MUNICIPAL DE SAO CAETANO DO SUL - USCS - LIMPEZA' },
  { centro_custo: '1126', contrato: 'VILA MARIA - LOGRADOUROS' },
  { centro_custo: '1368', contrato: 'VIVEIRO ARTHUR ETZEL' },
  { centro_custo: '1366', contrato: 'VIVEIRO MANEQUINHO LOPES' },
  { centro_custo: '1367', contrato: 'VIVEIROS HARRY BLOSSFELD' },
] as const

export const FUNCTION_OPTIONS = [
  'Operador de roçadeira',
  'Operador de motosserra',
  'Podador',
  'Jardineiro',
  'Tratorista',
] as const

export const DELIVERY_STATE_OPTIONS = [
  'Novo',
  'Bom estado',
  'Regular',
] as const
